# Generated by Django 5.0.2 on 2024-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_a', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_b', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_c', models.CharField(max_length=100)),
            ],
        ),
    ]
